---项目表
DROP TABLE IF EXISTS `tbl_project`;
CREATE TABLE `tbl_project`  (
  `PROJECT_ID` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目主键',
  `PROJECT_NO` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT '项目编号',
  `PROJECT_NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL COMMENT '项目名称',
  `PROJECT_THEME` varchar(500) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '项目主题',
  `PROJECT_DESC` varchar(1000) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '项目描述',
  `PROJECT_SPONSOR` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '项目发起者或者发起部门机构',
  `START_TIME` datetime(0) NULL DEFAULT NULL COMMENT '项目开始时间',
  `END_TIME` datetime(0) NULL DEFAULT NULL COMMENT '项目结束时间',
  `STATUS` int(1) NULL DEFAULT 0 COMMENT '项目状态 ：0 已创建未开始  1已开始 2结束  3撤销',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `USER_ID` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '创建人',
  `FILE_PATH` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '路线图相对路径',
  `IS_MAKER` int(255) NULL DEFAULT 0 COMMENT '是否创建路线图 0 否 1 是',
  PRIMARY KEY (`PROJECT_ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 10 CHARACTER SET = utf8 COLLATE = utf8_unicode_ci ROW_FORMAT = Dynamic;

----需求分析表
DROP TABLE IF EXISTS `tbl_analysis`;
CREATE TABLE `tbl_analysis`  (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `PROJECT_ID` int(11) NULL DEFAULT NULL COMMENT '关联项目 对应项目主键',
  `ANALYSIS_RESULT` varchar(500) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '分析结果',
  `ANALYSIS_BASE` varchar(500) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '分析依据',
  `ANALYSIS_BASE_NAME` varchar(500) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '分析依据对应的具体文档名称',
  `TYPE` int(1) NULL DEFAULT 1 COMMENT '分析类型：1 国内  2 国外',
  `STATUS` int(1) NULL DEFAULT 1 COMMENT '状态 0 无效 1有效',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = utf8 COLLATE = utf8_unicode_ci COMMENT = '需求分析表' ROW_FORMAT = Dynamic;
